apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: sovryn-graph-wrapper
  name: sovryn-graph-wrapper
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sovryn-graph-wrapper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sovryn-graph-wrapper
    spec:
      containers:
      - image: sovryn/sovryn-graph-wrapper
        imagePullPolicy: Always
        name: sovryn-graph-wrapper
        resources:
          requests:
            memory: "4096Mi"
            cpu: "200m"
          limits:
            memory: "4096Mi"
            cpu: "400m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: sovryn-graph-wrapper
        - secretRef:
            name: sovryn-graph-wrapper-secrets
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sovryn-graph-wrapper
spec:
  selector:
    app: sovryn-graph-wrapper
  ports:
    - port: 443
      targetPort: 3000
  type: NodePort
