apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: sov-boilerplate-service
  name: sov-boilerplate-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sov-boilerplate-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sov-boilerplate-service
    spec:
      containers:
      - image: gcr.io/sovryn-dev/sov-boilerplate-service:latest
        name: sov-boilerplate-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: PORT
          value: "3003"
        - name: URL_REDIS_SERVICE
          value: http://localhost
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
 
          
