version: '3.4'

services:
  sov-postgres:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sov-contract-data-main
    expose:
      - 5432
    networks:
      - sovryn

  sov-graph-wrapper-service:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - APP_NAME='margin-call-service'
      - LOG_LEVEL=debug
      - POSTGRES_HOST=sov-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sov-contract-data-main
    depends_on:
      - sov-postgres
    networks:
      - sovryn

networks:
  sovryn:
    driver: bridge
    ipam:
      driver: default