version: '3.4'

services:
  sov-postgres:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sov-boilerplate-main
    expose:
      - 5432
    networks:
      - sovryn

  sov-boilerplate-service:
    image: sov-boilerplate-service
    environment:
      - PORT=3000
      - URL_REDIS_SERVICE=http://sov-boilerplate-redis-service
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - sov-boilerplate-service-redis-service
    networks:
      - sovryn

networks:
  sovryn:
    driver: bridge
    ipam:
      driver: default
