version: '3.4'

services:
  sov-postgres:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sov-contract-data-main
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - sovryn

  sov-graph-wrapper-service:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - APP_NAME='graph-wrapper-service'
      - LOG_LEVEL=debug
      - POSTGRES_HOST=sov-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sov-contract-data-main
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - .env
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - sov-postgres
    networks:
      - sovryn
networks:
  sovryn:
    driver: bridge
    ipam:
      driver: default

